AWSTemplateFormatVersion: '2010-09-09'
Description: 'GPS Tracking - DynamoDB Tables'

Parameters:
  Environment:
    Type: String
  ProjectName:
    Type: String

Resources:
  PositionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-${Environment}-positions'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: truck_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: truck_id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  GeofencesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-${Environment}-geofences'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: geofence_id
          AttributeType: S
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: geofence_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: name-index
          KeySchema:
            - AttributeName: name
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  AlertsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-${Environment}-alerts'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: alert_id
          AttributeType: S
        - AttributeName: truck_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: alert_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: truck-timestamp-index
          KeySchema:
            - AttributeName: truck_id
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

Outputs:
  PositionsTableName:
    Description: Positions table name
    Value: !Ref PositionsTable

  PositionsTableArn:
    Description: Positions table ARN
    Value: !GetAtt PositionsTable.Arn

  GeofencesTableName:
    Description: Geofences table name
    Value: !Ref GeofencesTable

  GeofencesTableArn:
    Description: Geofences table ARN
    Value: !GetAtt GeofencesTable.Arn

  AlertsTableName:
    Description: Alerts table name
    Value: !Ref AlertsTable

  AlertsTableArn:
    Description: Alerts table ARN
    Value: !GetAtt AlertsTable.Arn
