AWSTemplateFormatVersion: '2010-09-09'
Description: 'GPS Tracking - SNS Topics'

Parameters:
  Environment:
    Type: String
  ProjectName:
    Type: String
  AlarmEmail:
    Type: String
    Default: ''

Conditions:
  HasAlarmEmail: !Not [!Equals [!Ref AlarmEmail, '']]

Resources:
  GeofenceAlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${ProjectName}-${Environment}-geofence-alerts'
      KmsMasterKeyId: alias/aws/sns
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  EmailSubscription:
    Type: AWS::SNS::Subscription
    Condition: HasAlarmEmail
    Properties:
      TopicArn: !Ref GeofenceAlertsTopic
      Protocol: email
      Endpoint: !Ref AlarmEmail

Outputs:
  TopicArn:
    Description: Geofence alerts topic ARN
    Value: !Ref GeofenceAlertsTopic

  TopicName:
    Description: Geofence alerts topic name
    Value: !GetAtt GeofenceAlertsTopic.TopicName
