AWSTemplateFormatVersion: '2010-09-09'
Description: 'SMS Marketing - CloudWatch Monitoring'

Parameters:
  Environment:
    Type: String
  ProjectName:
    Type: String
  CampaignSenderName:
    Type: String
  ResponseHandlerName:
    Type: String
  AnalyticsProcessorName:
    Type: String
  AlarmEmail:
    Type: String
    Default: ''

Conditions:
  HasEmail: !Not [!Equals [!Ref AlarmEmail, '']]

Resources:
  AlarmTopic:
    Type: AWS::SNS::Topic
    Condition: HasEmail
    Properties:
      TopicName: !Sub '${ProjectName}-${Environment}-alarms'

  CampaignSenderErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-${Environment}-campaign-sender-errors'
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref CampaignSenderName
      AlarmActions:
        - !If [HasEmail, !Ref AlarmTopic, !Ref 'AWS::NoValue']

  Dashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub '${ProjectName}-${Environment}-dashboard'
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "title": "Lambda Invocations",
                "metrics": [
                  ["AWS/Lambda", "Invocations", "FunctionName", "${CampaignSenderName}"],
                  [".", ".", ".", "${ResponseHandlerName}"],
                  [".", ".", ".", "${AnalyticsProcessorName}"]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "${AWS::Region}"
              }
            }
          ]
        }

Outputs:
  DashboardName:
    Value: !Ref Dashboard
