AWSTemplateFormatVersion: '2010-09-09'
Description: 'SMS Marketing - S3 Buckets'

Parameters:
  Environment:
    Type: String
  ProjectName:
    Type: String
  RetentionDays:
    Type: Number

Resources:
  ArchiveBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-${Environment}-archive-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: 30
          - Id: TransitionToGlacier
            Status: Enabled
            Transitions:
              - StorageClass: GLACIER
                TransitionInDays: 90

Outputs:
  ArchiveBucketName:
    Value: !Ref ArchiveBucket
  ArchiveBucketArn:
    Value: !GetAtt ArchiveBucket.Arn
