AWSTemplateFormatVersion: '2010-09-09'
Description: 'Enterprise Serverless Platform - Secrets Manager'

Parameters:
  Environment:
    Type: String
  ProjectName:
    Type: String
  KMSKeyArn:
    Type: String

Resources:
  # OAuth Secrets for Email Providers
  EmailOAuthSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}/${Environment}/email-oauth'
      Description: OAuth credentials for email providers (Microsoft 365, Google)
      KmsKeyId: !Ref KMSKeyArn
      SecretString: '{"microsoft365_client_id":"","microsoft365_client_secret":"","google_client_id":"","google_client_secret":""}'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-email-oauth'

  # CRM Integration Secrets
  CRMSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}/${Environment}/crm-credentials'
      Description: API credentials for CRM providers
      KmsKeyId: !Ref KMSKeyArn
      SecretString: '{"salesforce_client_id":"","salesforce_client_secret":"","hubspot_api_key":"","dynamics_client_id":"","dynamics_client_secret":""}'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-crm-credentials'

  # Application Secrets
  AppSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}/${Environment}/app-secrets'
      Description: Application secrets
      KmsKeyId: !Ref KMSKeyArn
      SecretString: '{"jwt_secret":"","encryption_key":"","webhook_secret":""}'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-app-secrets'

Outputs:
  EmailOAuthSecretsArn:
    Value: !Ref EmailOAuthSecrets
  CRMSecretsArn:
    Value: !Ref CRMSecrets
  AppSecretsArn:
    Value: !Ref AppSecrets
