AWSTemplateFormatVersion: '2010-09-09'
Description: 'Banking Platform - DynamoDB Tables'

Parameters:
  Environment:
    Type: String
  ProjectName:
    Type: String

Conditions:
  IsProd: !Equals [!Ref Environment, 'prod']

Resources:
  # Transactions Table
  TransactionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-${Environment}-transactions'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: transaction_id
          AttributeType: S
      KeySchema:
        - AttributeName: transaction_id
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !If [IsProd, true, false]
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-transactions'

  # Idempotency Table
  IdempotencyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-${Environment}-idempotency'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: idempotency_key
          AttributeType: S
      KeySchema:
        - AttributeName: idempotency_key
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-idempotency'

  # DLQ Records Table
  DlqRecordsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-${Environment}-dlq-records'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: message_id
          AttributeType: S
      KeySchema:
        - AttributeName: message_id
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-dlq-records'

Outputs:
  TransactionsTableArn:
    Value: !GetAtt TransactionsTable.Arn
  TransactionsTableName:
    Value: !Ref TransactionsTable
  IdempotencyTableArn:
    Value: !GetAtt IdempotencyTable.Arn
  IdempotencyTableName:
    Value: !Ref IdempotencyTable
  DlqRecordsTableArn:
    Value: !GetAtt DlqRecordsTable.Arn
  DlqRecordsTableName:
    Value: !Ref DlqRecordsTable
