AWSTemplateFormatVersion: '2010-09-09'
Description: 'ML Platform - SNS Topics'

Parameters:
  Environment:
    Type: String
  ProjectName:
    Type: String
  NotificationEmail:
    Type: String
    Default: ''

Conditions:
  HasEmail: !Not [!Equals [!Ref NotificationEmail, '']]

Resources:
  SuccessTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${ProjectName}-${Environment}-success'
      KmsMasterKeyId: alias/aws/sns
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-success'

  FailureTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${ProjectName}-${Environment}-failure'
      KmsMasterKeyId: alias/aws/sns
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-failure'

  AlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${ProjectName}-${Environment}-alerts'
      KmsMasterKeyId: alias/aws/sns
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-alerts'

  # Email subscriptions
  SuccessEmailSubscription:
    Type: AWS::SNS::Subscription
    Condition: HasEmail
    Properties:
      TopicArn: !Ref SuccessTopic
      Protocol: email
      Endpoint: !Ref NotificationEmail

  FailureEmailSubscription:
    Type: AWS::SNS::Subscription
    Condition: HasEmail
    Properties:
      TopicArn: !Ref FailureTopic
      Protocol: email
      Endpoint: !Ref NotificationEmail

  AlertEmailSubscription:
    Type: AWS::SNS::Subscription
    Condition: HasEmail
    Properties:
      TopicArn: !Ref AlertTopic
      Protocol: email
      Endpoint: !Ref NotificationEmail

Outputs:
  SuccessTopicArn:
    Value: !Ref SuccessTopic
  FailureTopicArn:
    Value: !Ref FailureTopic
  AlertTopicArn:
    Value: !Ref AlertTopic
