AWSTemplateFormatVersion: '2010-09-09'
Description: Athena Workgroup and Named Queries

Parameters:
  ProjectName:
    Type: String
  Environment:
    Type: String
  WorkgroupName:
    Type: String
  ResultsBucketName:
    Type: String
  DatabaseName:
    Type: String
  QueryTimeout:
    Type: Number
    Default: 300

Resources:
  # Athena Workgroup
  AthenaWorkgroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: !Ref WorkgroupName
      Description: !Sub 'Analytics workgroup for ${ProjectName}'
      State: ENABLED
      WorkGroupConfiguration:
        EnforceWorkGroupConfiguration: true
        PublishCloudWatchMetricsEnabled: true
        BytesScannedCutoffPerQuery: 10737418240  # 10 GB
        ResultConfiguration:
          OutputLocation: !Sub 's3://${ResultsBucketName}/athena-results/'
          EncryptionConfiguration:
            EncryptionOption: SSE_S3
        EngineVersion:
          SelectedEngineVersion: 'Athena engine version 3'

  # Named Query: Events by Type
  EventsByTypeQuery:
    Type: AWS::Athena::NamedQuery
    Properties:
      Name: events_by_type
      Description: Count events grouped by type
      Database: !Ref DatabaseName
      WorkGroup: !Ref AthenaWorkgroup
      QueryString: |
        SELECT
          event_type,
          COUNT(*) as event_count,
          COUNT(DISTINCT user_id) as unique_users
        FROM events
        WHERE year = CAST(YEAR(CURRENT_DATE) AS VARCHAR)
          AND month = LPAD(CAST(MONTH(CURRENT_DATE) AS VARCHAR), 2, '0')
        GROUP BY event_type
        ORDER BY event_count DESC

  # Named Query: Daily Active Users
  DailyActiveUsersQuery:
    Type: AWS::Athena::NamedQuery
    Properties:
      Name: daily_active_users
      Description: Calculate daily active users
      Database: !Ref DatabaseName
      WorkGroup: !Ref AthenaWorkgroup
      QueryString: |
        SELECT
          year,
          month,
          day,
          COUNT(DISTINCT user_id) as dau
        FROM events
        WHERE year = CAST(YEAR(CURRENT_DATE) AS VARCHAR)
        GROUP BY year, month, day
        ORDER BY year, month, day

  # Named Query: User Sessions
  UserSessionsQuery:
    Type: AWS::Athena::NamedQuery
    Properties:
      Name: user_sessions
      Description: Analyze user session patterns
      Database: !Ref DatabaseName
      WorkGroup: !Ref AthenaWorkgroup
      QueryString: |
        SELECT
          user_id,
          session_id,
          MIN(timestamp) as session_start,
          MAX(timestamp) as session_end,
          COUNT(*) as event_count,
          date_diff('minute', MIN(timestamp), MAX(timestamp)) as session_duration_minutes
        FROM events
        WHERE year = CAST(YEAR(CURRENT_DATE) AS VARCHAR)
          AND session_id IS NOT NULL
        GROUP BY user_id, session_id
        ORDER BY session_start DESC
        LIMIT 100

  # Named Query: Data Quality Check
  DataQualityQuery:
    Type: AWS::Athena::NamedQuery
    Properties:
      Name: data_quality_check
      Description: Check data quality metrics
      Database: !Ref DatabaseName
      WorkGroup: !Ref AthenaWorkgroup
      QueryString: |
        SELECT
          year,
          month,
          day,
          COUNT(*) as total_records,
          COUNT(CASE WHEN event_id IS NULL THEN 1 END) as null_event_ids,
          COUNT(CASE WHEN user_id IS NULL THEN 1 END) as null_user_ids,
          COUNT(DISTINCT event_type) as unique_event_types
        FROM events
        GROUP BY year, month, day
        ORDER BY year DESC, month DESC, day DESC
        LIMIT 30

Outputs:
  WorkgroupName:
    Description: Name of the Athena workgroup
    Value: !Ref AthenaWorkgroup

  WorkgroupArn:
    Description: ARN of the Athena workgroup
    Value: !GetAtt AthenaWorkgroup.WorkGroupConfiguration.EngineVersion.EffectiveEngineVersion

  ResultsLocation:
    Description: S3 location for query results
    Value: !Sub 's3://${ResultsBucketName}/athena-results/'
