AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: GenAI Knowledge Assistant - RAG-powered enterprise knowledge management

# =============================================================================
# Parameters
# =============================================================================

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name

  ProjectName:
    Type: String
    Default: genai-assistant
    Description: Project name for resource naming

  BedrockModelId:
    Type: String
    Default: anthropic.claude-3-5-sonnet-20241022-v2:0
    Description: Bedrock foundation model ID

  BedrockEmbeddingModelId:
    Type: String
    Default: amazon.titan-embed-text-v2:0
    Description: Bedrock embedding model ID

  VectorDimension:
    Type: Number
    Default: 1024
    Description: Vector dimension for embeddings

# =============================================================================
# Globals
# =============================================================================

Globals:
  Function:
    Runtime: python3.12
    Timeout: 60
    MemorySize: 512
    Tracing: Active
    Architectures:
      - x86_64
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        AWS_REGION: !Ref AWS::Region
        LOG_LEVEL: !If [IsProd, INFO, DEBUG]
        POWERTOOLS_SERVICE_NAME: !Ref ProjectName
        POWERTOOLS_METRICS_NAMESPACE: GenAIKnowledgeAssistant
        BEDROCK_MODEL_ID: !Ref BedrockModelId
        BEDROCK_EMBEDDING_MODEL_ID: !Ref BedrockEmbeddingModelId
        DOCUMENTS_BUCKET: !Ref DocumentsBucket
        DOCUMENTS_TABLE: !Ref DocumentsTable
        CONVERSATIONS_TABLE: !Ref ConversationsTable
        OPENSEARCH_VECTOR_DIMENSION: !Ref VectorDimension

# =============================================================================
# Conditions
# =============================================================================

Conditions:
  IsProd: !Equals [!Ref Environment, prod]

# =============================================================================
# Resources
# =============================================================================

Resources:

  # ===========================================================================
  # S3 Buckets
  # ===========================================================================

  DocumentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ProjectName}-${Environment}-documents-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: 90

  # ===========================================================================
  # DynamoDB Tables
  # ===========================================================================

  DocumentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${ProjectName}-${Environment}-documents
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: documentId
          AttributeType: S
        - AttributeName: knowledgeBaseId
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: documentId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: knowledgeBaseId-index
          KeySchema:
            - AttributeName: knowledgeBaseId
              KeyType: HASH
            - AttributeName: documentId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: status-index
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: documentId
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !If [IsProd, true, false]
      SSESpecification:
        SSEEnabled: true

  ConversationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${ProjectName}-${Environment}-conversations
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: conversationId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: conversationId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: userId-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: conversationId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      SSESpecification:
        SSEEnabled: true

  # ===========================================================================
  # Lambda Functions
  # ===========================================================================

  ApiHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ProjectName}-${Environment}-api-handler
      CodeUri: ../src/
      Handler: handlers.api_handler.handler
      Description: API Gateway handler for REST endpoints
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DocumentsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ConversationsTable
        - S3CrudPolicy:
            BucketName: !Ref DocumentsBucket
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:Retrieve
                - bedrock:RetrieveAndGenerate
              Resource: '*'
        - Statement:
            - Effect: Allow
              Action:
                - aoss:APIAccessAll
              Resource: '*'
      Events:
        ApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /
            Method: ANY
        ApiProxy:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /{proxy+}
            Method: ANY

  QueryHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ProjectName}-${Environment}-query-handler
      CodeUri: ../src/
      Handler: handlers.query_handler.handler
      Description: Query handler for RAG queries
      Timeout: 120
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DocumentsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ConversationsTable
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
                - bedrock:Retrieve
                - bedrock:RetrieveAndGenerate
              Resource: '*'
        - Statement:
            - Effect: Allow
              Action:
                - aoss:APIAccessAll
              Resource: '*'

  IngestionHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ProjectName}-${Environment}-ingestion-handler
      CodeUri: ../src/
      Handler: handlers.ingestion_handler.handler
      Description: Document ingestion handler
      Timeout: 300
      MemorySize: 1024
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DocumentsTable
        - S3CrudPolicy:
            BucketName: !Ref DocumentsBucket
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: '*'
        - Statement:
            - Effect: Allow
              Action:
                - aoss:APIAccessAll
              Resource: '*'
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref DocumentsBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: documents/

  AgentHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ProjectName}-${Environment}-agent-handler
      CodeUri: ../src/
      Handler: handlers.agent_handler.handler
      Description: Bedrock Agent interaction handler
      Timeout: 120
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConversationsTable
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeAgent
              Resource: '*'
      Events:
        AgentApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /agent
            Method: POST

  SyncHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ProjectName}-${Environment}-sync-handler
      CodeUri: ../src/
      Handler: handlers.sync_handler.handler
      Description: Knowledge base sync handler
      MemorySize: 256
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:StartIngestionJob
                - bedrock:GetIngestionJob
                - bedrock:ListIngestionJobs
              Resource: '*'
      Events:
        DailySync:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
            Enabled: false

  # ===========================================================================
  # API Gateway
  # ===========================================================================

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${ProjectName}-${Environment}-api
      StageName: !Ref Environment
      TracingEnabled: true
      AccessLogSetting:
        DestinationArn: !GetAtt ApiAccessLogGroup.Arn
        Format: '{"requestId":"$context.requestId","ip":"$context.identity.sourceIp","requestTime":"$context.requestTime","httpMethod":"$context.httpMethod","path":"$context.resourcePath","status":"$context.status","responseLatency":"$context.responseLatency"}'
      MethodSettings:
        - ResourcePath: /*
          HttpMethod: '*'
          ThrottlingBurstLimit: 200
          ThrottlingRateLimit: 100
          MetricsEnabled: true
          LoggingLevel: INFO

  ApiAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/apigateway/${ProjectName}-${Environment}-api-access
      RetentionInDays: 30

# =============================================================================
# Outputs
# =============================================================================

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}

  DocumentsBucketName:
    Description: Documents S3 bucket name
    Value: !Ref DocumentsBucket

  DocumentsTableName:
    Description: Documents DynamoDB table name
    Value: !Ref DocumentsTable

  ConversationsTableName:
    Description: Conversations DynamoDB table name
    Value: !Ref ConversationsTable

  ApiHandlerArn:
    Description: API handler Lambda ARN
    Value: !GetAtt ApiHandlerFunction.Arn

  QueryHandlerArn:
    Description: Query handler Lambda ARN
    Value: !GetAtt QueryHandlerFunction.Arn

  IngestionHandlerArn:
    Description: Ingestion handler Lambda ARN
    Value: !GetAtt IngestionHandlerFunction.Arn
