AWSTemplateFormatVersion: '2010-09-09'
Description: S3 resources for GenAI Knowledge Assistant

Parameters:
  ProjectName:
    Type: String
    Description: Project name for resource naming

  Environment:
    Type: String
    Description: Deployment environment

Resources:
  # Documents Bucket
  DocumentsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub '${ProjectName}-${Environment}-documents-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: 90
            NoncurrentVersionExpiration:
              NoncurrentDays: 30
          - Id: DeleteIncompleteMultipart
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
            AllowedOrigins:
              - '*'
            MaxAge: 3000
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # Bucket Policy
  DocumentsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DocumentsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: EnforceSSL
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !GetAtt DocumentsBucket.Arn
              - !Sub '${DocumentsBucket.Arn}/*'
            Condition:
              Bool:
                'aws:SecureTransport': 'false'
          - Sid: EnforceEncryption
            Effect: Deny
            Principal: '*'
            Action: 's3:PutObject'
            Resource: !Sub '${DocumentsBucket.Arn}/*'
            Condition:
              StringNotEquals:
                's3:x-amz-server-side-encryption': 'AES256'
              'Null':
                's3:x-amz-server-side-encryption': 'false'

Outputs:
  DocumentsBucketName:
    Description: Name of the documents bucket
    Value: !Ref DocumentsBucket

  DocumentsBucketArn:
    Description: ARN of the documents bucket
    Value: !GetAtt DocumentsBucket.Arn

  DocumentsBucketDomainName:
    Description: Domain name of the documents bucket
    Value: !GetAtt DocumentsBucket.DomainName
