AWSTemplateFormatVersion: '2010-09-09'
Description: 'Task Automation - CloudWatch Monitoring'

Parameters:
  Environment:
    Type: String
  ProjectName:
    Type: String
  TaskGeneratorName:
    Type: String
  SQSProcessorName:
    Type: String
  TaskExecutorName:
    Type: String
  NotificationHandlerName:
    Type: String
  StateMachineName:
    Type: String
  AlarmEmail:
    Type: String
    Default: ''

Conditions:
  HasEmail: !Not [!Equals [!Ref AlarmEmail, '']]

Resources:
  AlarmTopic:
    Type: AWS::SNS::Topic
    Condition: HasEmail
    Properties:
      TopicName: !Sub '${ProjectName}-${Environment}-alarms'

  AlarmSubscription:
    Type: AWS::SNS::Subscription
    Condition: HasEmail
    Properties:
      TopicArn: !Ref AlarmTopic
      Protocol: email
      Endpoint: !Ref AlarmEmail

  StepFunctionsFailedAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-${Environment}-stepfunctions-failed'
      MetricName: ExecutionsFailed
      Namespace: AWS/States
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 3
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: StateMachineArn
          Value: !Sub 'arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${StateMachineName}'
      AlarmActions:
        - !If [HasEmail, !Ref AlarmTopic, !Ref 'AWS::NoValue']

  Dashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub '${ProjectName}-${Environment}-dashboard'
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "title": "Step Functions Executions",
                "metrics": [
                  ["AWS/States", "ExecutionsStarted", "StateMachineArn", "arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${StateMachineName}"],
                  [".", "ExecutionsSucceeded", ".", "."],
                  [".", "ExecutionsFailed", ".", "."]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "${AWS::Region}"
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "title": "Lambda Invocations",
                "metrics": [
                  ["AWS/Lambda", "Invocations", "FunctionName", "${TaskGeneratorName}"],
                  [".", ".", ".", "${SQSProcessorName}"],
                  [".", ".", ".", "${TaskExecutorName}"],
                  [".", ".", ".", "${NotificationHandlerName}"]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "${AWS::Region}"
              }
            }
          ]
        }

Outputs:
  DashboardName:
    Value: !Ref Dashboard
