AWSTemplateFormatVersion: '2010-09-09'
Description: 'Task Automation - DynamoDB Tables'

Parameters:
  Environment:
    Type: String
  ProjectName:
    Type: String

Resources:
  TasksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-${Environment}-tasks'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: task_id
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: created_at
          AttributeType: S
      KeySchema:
        - AttributeName: task_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: status-created-index
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

Outputs:
  TasksTableName:
    Description: Tasks table name
    Value: !Ref TasksTable

  TasksTableArn:
    Description: Tasks table ARN
    Value: !GetAtt TasksTable.Arn

  TasksTableStreamArn:
    Description: Tasks table stream ARN
    Value: !GetAtt TasksTable.StreamArn
